package:
  name: ddrage
  version: "1.2.1"

source:
  fn: ddrage-1.2.1.tar.gz
  url: https://pypi.python.org/packages/71/1f/e0e9ca9d073bfe31cf6d0163661eaa7cd3994d5ab0933b2e0bc2fef73e58/ddrage-1.2.1.tar.gz
  md5: 2e50c492791c26a7f206f73e5eec8b52

build:
  skip: True # [py2k or py34]
  entry_points:
    - rage = ddrage.__main__:main
    - randomize_fastq = ddrage.tools.randomize_fastq:main
    - learn_qmodel = ddrage.tools.learn_qmodel:main
    - visualize_bbd = ddrage.tools.bbd_visualization:main_standalone
    - remove_annotation = ddrage.tools.remove_annotation:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - numba
    - matplotlib
    - scipy
    - pyyaml
    - libgcc

  run:
    - python
    - numpy
    - numba
    - matplotlib
    - scipy
    - pyyaml
    - libgcc

test:
  imports:
    - ddrage
    - ddrage.barcode_handler
    - ddrage.tools

  commands:
    - rage -v
    - randomize_fastq --help
    - learn_qmodel --help
    # - visualize_bbd --help  # adding bokeh as a hard dependency made the build stall.
    - remove_annotation --help

about:
  home: https://bitbucket.org/genomeinformatics/rage
  license: MIT License
  summary: 'Simulator for ddRADseq (double digest restriction site associdated DNA squencing) datasets. Generates reads (FASTQ format) that can be analyzed and validated using a ground truth file (YAML).'
  license_family: MIT
